services:
  api-gateway:
    build: ./api-gateway
    env_file: .env
    environment:
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL:-http://auth-service:3001}
      OWNER_SERVICE_URL: ${OWNER_SERVICE_URL:-http://owner-service:3002}
      CUSTOMER_SERVICE_URL: ${CUSTOMER_SERVICE_URL:-http://customer-service:3003}
      PAYMENT_SERVICE_URL: ${PAYMENT_SERVICE_URL:-http://payment-service:3004}
      REVIEW_SERVICE_URL: ${REVIEW_SERVICE_URL:-http://review-service:3005}
    ports:
      - "3000:3000"

  auth-service:
    build: ./auth-service
    env_file: .env
    ports:
      - "3001:3001"

  owner-service:
    build: ./owner-service
    env_file: .env
    ports:
      - "3002:3002"

  customer-service:
    build: ./customer-service
    env_file: .env
    ports:
      - "3003:3003"

  payment-service:
    build: ./payment-service
    env_file: .env
    ports:
      - "3004:3004"

  review-service:
    build: ./review-service
    env_file: .env
    ports:
      - "3005:3005"
